version: '3.8'

services:
  nginx:
    networks:
      - proxy
    image: ghcr.io/malavisto/anilist-randomizer:main 
#    build: 
#      context: .
#      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.anilist-randomizer.rule=Host(`projects.domain.tld`) && PathPrefix(`/anilist-randomizer`)"
      - "traefik.http.routers.anilist-randomizer.entrypoints=https"
      - "traefik.http.routers.anilist-randomizer.tls=true"
networks:
  proxy:
      external: true
